/**
 * Everything the box can be asked to do with git, as data: one entry per action, by the object
 * it acts on and the verb it does. The understanding (model.ts), the slot readers (slots.ts), the
 * plan (understand.ts) and the doing (git/do.ts) all read this list, so an action exists once.
 *
 * An action is a verb on an object -- close an issue, merge a pull request, push a branch. The
 * model reads the verb and the object separately and only pairs that are here can be the answer,
 * so "close" said of a pull request is never closing an issue, and a new object or verb learnt
 * from one language's sentences carries to the others.
 *
 * Where an action happens: on the service (GitHub, GitLab, Gitea), on a clone on this machine,
 * or either -- a branch can be made on both, and which one is meant is read from the sentence and
 * from where grimstroke is standing (see understand.ts).
 */

export const GIT_OBJECTS = [
  'issue',
  'pr',
  'branch',
  'commit',
  'ci',
  'release',
  'tag',
  'label',
  'milestone',
  'repo',
  'file',
  'code',
  'member',
  'notification',
  'account',
  /** The working copy on this machine: its changes, its stash, its remotes. */
  'local',
] as const;
export type GitObject = (typeof GIT_OBJECTS)[number];

export const GIT_VERBS = [
  'create',
  'list',
  'show',
  'close',
  'reopen',
  'comment',
  'assign',
  'unassign',
  'label',
  'unlabel',
  'edit',
  'milestone',
  'lock',
  'unlock',
  'diff',
  'merge',
  'approve',
  'request-changes',
  'request-review',
  'ready',
  'checkout',
  'delete',
  'switch',
  'rename',
  'compare',
  'status',
  'rerun',
  'cancel',
  'fork',
  'star',
  'unstar',
  'clone',
  'search',
  'read',
  'connect',
  'disconnect',
  'whoami',
  'stage',
  'unstage',
  'commit',
  'amend',
  'push',
  'pull',
  'fetch',
  'rebase',
  'stash',
  'unstash',
  'reset',
  'discard',
  'cherry-pick',
  'revert',
  'blame',
  'init',
  'remote-add',
] as const;
export type GitVerb = (typeof GIT_VERBS)[number];

/** What an action is told: read from the sentence (slots.ts) or from what was said before. */
export type SlotName =
  | 'repo'
  | 'number'
  | 'people'
  | 'labels'
  | 'title'
  | 'body'
  | 'branch'
  | 'base'
  | 'ref'
  | 'tag'
  | 'path'
  | 'state'
  | 'mine'
  | 'author'
  | 'query'
  | 'milestone'
  | 'provider'
  | 'host'
  | 'count'
  | 'colour'
  | 'url'
  | 'draft'
  | 'force'
  | 'method'
  | 'type'
  | 'private';

/** Where it is done. */
export type Scope = 'remote' | 'local' | 'both' | 'account';

/**
 * How much doing it changes: `read` only looks; `write` changes something that can be changed
 * back; `destructive` loses something -- a deleted branch, a reset, a force push -- and is never
 * done without being asked again in so many words.
 */
export type Weight = 'read' | 'write' | 'destructive';

export interface GitAction {
  id: string;
  object: GitObject;
  verb: GitVerb;
  scope: Scope;
  weight: Weight;
  /** Slots it cannot be done without; asked for when the sentence and the context lack them. */
  needs: SlotName[];
  /** Slots it reads when they are there. */
  takes: SlotName[];
  en: string;
  fa: string;
  ru: string;
}

type Row = [
  object: GitObject,
  verb: GitVerb,
  scope: Scope,
  weight: Weight,
  needs: SlotName[],
  takes: SlotName[],
  en: string,
  fa: string,
  ru: string,
];

// prettier-ignore
const ROWS: Row[] = [
  // ------------------------------------------------------------ issues
  [
    'issue',
    'create',
    'remote',
    'write',
    ['title'],
    ['repo', 'body', 'labels', 'type', 'people', 'milestone'],
    'Open an issue',
    'ساختن ایشو',
    'Создать задачу',
  ],
  [
    'issue',
    'list',
    'remote',
    'read',
    [],
    ['repo', 'state', 'mine', 'author', 'labels', 'people', 'query', 'milestone', 'count'],
    'List issues',
    'فهرست ایشوها',
    'Список задач',
  ],
  [
    'issue',
    'show',
    'remote',
    'read',
    ['number'],
    ['repo'],
    'Show an issue',
    'نمایش ایشو',
    'Показать задачу',
  ],
  [
    'issue',
    'close',
    'remote',
    'write',
    ['number'],
    ['repo', 'body'],
    'Close an issue',
    'بستن ایشو',
    'Закрыть задачу',
  ],
  [
    'issue',
    'reopen',
    'remote',
    'write',
    ['number'],
    ['repo'],
    'Reopen an issue',
    'بازکردن دوباره‌ی ایشو',
    'Переоткрыть задачу',
  ],
  [
    'issue',
    'comment',
    'remote',
    'write',
    ['number', 'body'],
    ['repo'],
    'Comment on an issue',
    'کامنت روی ایشو',
    'Комментарий к задаче',
  ],
  [
    'issue',
    'assign',
    'remote',
    'write',
    ['number', 'people'],
    ['repo'],
    'Assign an issue',
    'اساین کردن ایشو',
    'Назначить задачу',
  ],
  [
    'issue',
    'unassign',
    'remote',
    'write',
    ['number', 'people'],
    ['repo'],
    'Unassign an issue',
    'برداشتن مسئول ایشو',
    'Снять назначение',
  ],
  [
    'issue',
    'label',
    'remote',
    'write',
    ['number', 'labels'],
    ['repo'],
    'Label an issue',
    'لیبل زدن به ایشو',
    'Добавить метки',
  ],
  [
    'issue',
    'unlabel',
    'remote',
    'write',
    ['number', 'labels'],
    ['repo'],
    'Remove a label',
    'برداشتن لیبل ایشو',
    'Убрать метки',
  ],
  [
    'issue',
    'edit',
    'remote',
    'write',
    ['number'],
    ['repo', 'title', 'body'],
    'Edit an issue',
    'ویرایش ایشو',
    'Изменить задачу',
  ],
  [
    'issue',
    'milestone',
    'remote',
    'write',
    ['number', 'milestone'],
    ['repo'],
    'Set the milestone',
    'تعیین مایلستون ایشو',
    'Назначить веху',
  ],
  [
    'issue',
    'lock',
    'remote',
    'write',
    ['number'],
    ['repo'],
    'Lock an issue',
    'قفل کردن ایشو',
    'Заблокировать обсуждение',
  ],
  [
    'issue',
    'unlock',
    'remote',
    'write',
    ['number'],
    ['repo'],
    'Unlock an issue',
    'باز کردن قفل ایشو',
    'Разблокировать обсуждение',
  ],
  // ------------------------------------------------------------ pull and merge requests
  [
    'pr',
    'create',
    'remote',
    'write',
    ['branch'],
    ['repo', 'base', 'title', 'body', 'draft', 'people', 'labels'],
    'Open a pull request',
    'ساختن پول ریکوئست',
    'Создать пул-реквест',
  ],
  [
    'pr',
    'list',
    'remote',
    'read',
    [],
    ['repo', 'state', 'mine', 'author', 'labels', 'people', 'query', 'count'],
    'List pull requests',
    'فهرست پول ریکوئست‌ها',
    'Список пул-реквестов',
  ],
  [
    'pr',
    'show',
    'remote',
    'read',
    ['number'],
    ['repo'],
    'Show a pull request',
    'نمایش پول ریکوئست',
    'Показать пул-реквест',
  ],
  [
    'pr',
    'diff',
    'remote',
    'read',
    ['number'],
    ['repo', 'path'],
    'Files a pull request changes',
    'تغییرات پول ریکوئست',
    'Изменения пул-реквеста',
  ],
  [
    'pr',
    'close',
    'remote',
    'write',
    ['number'],
    ['repo', 'body'],
    'Close a pull request',
    'بستن پول ریکوئست',
    'Закрыть пул-реквест',
  ],
  [
    'pr',
    'reopen',
    'remote',
    'write',
    ['number'],
    ['repo'],
    'Reopen a pull request',
    'بازکردن دوباره‌ی پول ریکوئست',
    'Переоткрыть пул-реквест',
  ],
  [
    'pr',
    'comment',
    'remote',
    'write',
    ['number', 'body'],
    ['repo'],
    'Comment on a pull request',
    'کامنت روی پول ریکوئست',
    'Комментарий к пул-реквесту',
  ],
  [
    'pr',
    'merge',
    'remote',
    'write',
    ['number'],
    ['repo', 'method', 'body'],
    'Merge a pull request',
    'مرج پول ریکوئست',
    'Слить пул-реквест',
  ],
  [
    'pr',
    'approve',
    'remote',
    'write',
    ['number'],
    ['repo', 'body'],
    'Approve a pull request',
    'تأیید پول ریکوئست',
    'Одобрить пул-реквест',
  ],
  [
    'pr',
    'request-changes',
    'remote',
    'write',
    ['number', 'body'],
    ['repo'],
    'Ask for changes',
    'درخواست تغییر در پول ریکوئست',
    'Запросить изменения',
  ],
  [
    'pr',
    'request-review',
    'remote',
    'write',
    ['number', 'people'],
    ['repo'],
    'Ask for a review',
    'درخواست ریویو',
    'Запросить ревью',
  ],
  [
    'pr',
    'assign',
    'remote',
    'write',
    ['number', 'people'],
    ['repo'],
    'Assign a pull request',
    'اساین کردن پول ریکوئست',
    'Назначить пул-реквест',
  ],
  [
    'pr',
    'label',
    'remote',
    'write',
    ['number', 'labels'],
    ['repo'],
    'Label a pull request',
    'لیبل زدن به پول ریکوئست',
    'Метки пул-реквеста',
  ],
  [
    'pr',
    'edit',
    'remote',
    'write',
    ['number'],
    ['repo', 'title', 'body', 'base'],
    'Edit a pull request',
    'ویرایش پول ریکوئست',
    'Изменить пул-реквест',
  ],
  [
    'pr',
    'ready',
    'remote',
    'write',
    ['number'],
    ['repo'],
    'Mark ready for review',
    'آماده‌ی ریویو کردن',
    'Готов к ревью',
  ],
  [
    'pr',
    'checkout',
    'local',
    'write',
    ['number'],
    ['repo'],
    'Check out a pull request',
    'چک‌اوت پول ریکوئست',
    'Переключиться на пул-реквест',
  ],
  // ------------------------------------------------------------ branches
  [
    'branch',
    'list',
    'both',
    'read',
    [],
    ['repo', 'query'],
    'List branches',
    'فهرست برنچ‌ها',
    'Список веток',
  ],
  [
    'branch',
    'create',
    'both',
    'write',
    ['branch'],
    ['repo', 'ref'],
    'Make a branch',
    'ساختن برنچ',
    'Создать ветку',
  ],
  [
    'branch',
    'delete',
    'both',
    'destructive',
    ['branch'],
    ['repo', 'force'],
    'Delete a branch',
    'حذف برنچ',
    'Удалить ветку',
  ],
  [
    'branch',
    'switch',
    'local',
    'write',
    ['branch'],
    [],
    'Switch to a branch',
    'رفتن به برنچ',
    'Переключиться на ветку',
  ],
  [
    'branch',
    'rename',
    'both',
    'write',
    ['branch', 'title'],
    ['repo'],
    'Rename a branch',
    'تغییر نام برنچ',
    'Переименовать ветку',
  ],
  // ------------------------------------------------------------ commits
  [
    'commit',
    'list',
    'both',
    'read',
    [],
    ['repo', 'branch', 'author', 'path', 'count'],
    'Recent commits',
    'کامیت‌های اخیر',
    'Последние коммиты',
  ],
  [
    'commit',
    'show',
    'both',
    'read',
    ['ref'],
    ['repo'],
    'Show a commit',
    'نمایش کامیت',
    'Показать коммит',
  ],
  [
    'commit',
    'compare',
    'both',
    'read',
    ['ref', 'base'],
    ['repo'],
    'Compare two refs',
    'مقایسه‌ی دو برنچ',
    'Сравнить ветки',
  ],
  // ------------------------------------------------------------ CI
  [
    'ci',
    'status',
    'remote',
    'read',
    [],
    ['repo', 'branch', 'number', 'ref'],
    'Did CI pass?',
    'وضعیت CI',
    'Статус CI',
  ],
  [
    'ci',
    'list',
    'remote',
    'read',
    [],
    ['repo', 'branch', 'state', 'count'],
    'CI runs',
    'اجراهای CI',
    'Запуски CI',
  ],
  [
    'ci',
    'rerun',
    'remote',
    'write',
    [],
    ['repo', 'branch', 'number', 'ref'],
    'Run CI again',
    'اجرای دوباره‌ی CI',
    'Перезапустить CI',
  ],
  [
    'ci',
    'cancel',
    'remote',
    'write',
    [],
    ['repo', 'branch', 'number', 'ref'],
    'Cancel a CI run',
    'لغو اجرای CI',
    'Отменить CI',
  ],
  // ------------------------------------------------------------ releases and tags
  ['release', 'list', 'remote', 'read', [], ['repo', 'count'], 'Releases', 'ریلیزها', 'Релизы'],
  [
    'release',
    'show',
    'remote',
    'read',
    [],
    ['repo', 'tag'],
    'Show a release',
    'نمایش ریلیز',
    'Показать релиз',
  ],
  [
    'release',
    'create',
    'remote',
    'write',
    ['tag'],
    ['repo', 'title', 'body', 'ref', 'draft'],
    'Make a release',
    'ساختن ریلیز',
    'Создать релиз',
  ],
  [
    'release',
    'delete',
    'remote',
    'destructive',
    ['tag'],
    ['repo'],
    'Delete a release',
    'حذف ریلیز',
    'Удалить релиз',
  ],
  ['tag', 'list', 'both', 'read', [], ['repo', 'count'], 'Tags', 'تگ‌ها', 'Теги'],
  [
    'tag',
    'create',
    'both',
    'write',
    ['tag'],
    ['repo', 'ref', 'body'],
    'Make a tag',
    'ساختن تگ',
    'Создать тег',
  ],
  [
    'tag',
    'delete',
    'both',
    'destructive',
    ['tag'],
    ['repo'],
    'Delete a tag',
    'حذف تگ',
    'Удалить тег',
  ],
  // ------------------------------------------------------------ labels and milestones
  [
    'label',
    'list',
    'remote',
    'read',
    [],
    ['repo'],
    'A repository’s labels',
    'لیبل‌های ریپو',
    'Метки репозитория',
  ],
  [
    'label',
    'create',
    'remote',
    'write',
    ['labels'],
    ['repo', 'colour', 'body'],
    'Make a label',
    'ساختن لیبل',
    'Создать метку',
  ],
  [
    'label',
    'delete',
    'remote',
    'destructive',
    ['labels'],
    ['repo'],
    'Delete a label',
    'حذف لیبل',
    'Удалить метку',
  ],
  [
    'label',
    'edit',
    'remote',
    'write',
    ['labels'],
    ['repo', 'title', 'colour', 'body'],
    'Change a label',
    'ویرایش لیبل',
    'Изменить метку',
  ],
  [
    'milestone',
    'list',
    'remote',
    'read',
    [],
    ['repo', 'state'],
    'Milestones',
    'مایلستون‌ها',
    'Вехи',
  ],
  [
    'milestone',
    'create',
    'remote',
    'write',
    ['milestone'],
    ['repo', 'body'],
    'Make a milestone',
    'ساختن مایلستون',
    'Создать веху',
  ],
  [
    'milestone',
    'close',
    'remote',
    'write',
    ['milestone'],
    ['repo'],
    'Close a milestone',
    'بستن مایلستون',
    'Закрыть веху',
  ],
  // ------------------------------------------------------------ repositories
  [
    'repo',
    'list',
    'remote',
    'read',
    [],
    ['query', 'provider'],
    'Repositories',
    'ریپوها',
    'Репозитории',
  ],
  [
    'repo',
    'show',
    'remote',
    'read',
    [],
    ['repo'],
    'About a repository',
    'درباره‌ی ریپو',
    'О репозитории',
  ],
  [
    'repo',
    'create',
    'remote',
    'write',
    ['repo'],
    ['body', 'private', 'provider'],
    'Make a repository',
    'ساختن ریپو',
    'Создать репозиторий',
  ],
  [
    'repo',
    'fork',
    'remote',
    'write',
    ['repo'],
    [],
    'Fork a repository',
    'فورک کردن ریپو',
    'Форкнуть репозиторий',
  ],
  [
    'repo',
    'star',
    'remote',
    'write',
    ['repo'],
    [],
    'Star a repository',
    'ستاره دادن به ریپو',
    'Поставить звезду',
  ],
  [
    'repo',
    'unstar',
    'remote',
    'write',
    ['repo'],
    [],
    'Unstar a repository',
    'برداشتن ستاره',
    'Убрать звезду',
  ],
  [
    'repo',
    'delete',
    'remote',
    'destructive',
    ['repo'],
    [],
    'Delete a repository',
    'حذف ریپو',
    'Удалить репозиторий',
  ],
  [
    'repo',
    'clone',
    'local',
    'write',
    ['repo'],
    ['path', 'branch'],
    'Clone a repository',
    'کلون کردن ریپو',
    'Клонировать репозиторий',
  ],
  // ------------------------------------------------------------ reading code, people
  [
    'file',
    'show',
    'both',
    'read',
    ['path'],
    ['repo', 'ref'],
    'Show a file',
    'نمایش فایل',
    'Показать файл',
  ],
  [
    'file',
    'blame',
    'local',
    'read',
    ['path'],
    [],
    'Who wrote each line',
    'بلیم فایل',
    'Кто писал строки',
  ],
  [
    'code',
    'search',
    'remote',
    'read',
    ['query'],
    ['repo'],
    'Search the code',
    'جست‌وجو در کد',
    'Поиск по коду',
  ],
  ['member', 'list', 'remote', 'read', [], ['repo'], 'Who works on it', 'اعضای ریپو', 'Участники'],
  [
    'notification',
    'list',
    'account',
    'read',
    [],
    ['repo', 'provider'],
    'Notifications',
    'اعلان‌ها',
    'Уведомления',
  ],
  [
    'notification',
    'read',
    'account',
    'write',
    [],
    ['repo', 'provider'],
    'Mark notifications read',
    'خوانده کردن اعلان‌ها',
    'Прочитать уведомления',
  ],
  // ------------------------------------------------------------ accounts
  [
    'account',
    'connect',
    'account',
    'write',
    [],
    ['provider', 'host'],
    'Connect an account',
    'وصل کردن حساب',
    'Подключить аккаунт',
  ],
  [
    'account',
    'list',
    'account',
    'read',
    [],
    [],
    'Connected accounts',
    'حساب‌های وصل',
    'Подключённые аккаунты',
  ],
  [
    'account',
    'disconnect',
    'account',
    'destructive',
    ['host'],
    ['provider'],
    'Disconnect an account',
    'قطع حساب',
    'Отключить аккаунт',
  ],
  [
    'account',
    'whoami',
    'account',
    'read',
    [],
    ['provider', 'host'],
    'Who am I signed in as',
    'با چه حسابی وصلم',
    'Под кем я вошёл',
  ],
  // ------------------------------------------------------------ the working copy here
  ['local', 'status', 'local', 'read', [], [], 'What changed here', 'وضعیت تغییرات', 'Статус'],
  [
    'local',
    'diff',
    'local',
    'read',
    [],
    ['path', 'ref'],
    'The changes, line by line',
    'دیف تغییرات',
    'Изменения',
  ],
  [
    'local',
    'stage',
    'local',
    'write',
    [],
    ['path'],
    'Stage changes',
    'استیج کردن',
    'Добавить в индекс',
  ],
  [
    'local',
    'unstage',
    'local',
    'write',
    [],
    ['path'],
    'Unstage changes',
    'آن‌استیج کردن',
    'Убрать из индекса',
  ],
  ['local', 'commit', 'local', 'write', ['body'], ['path'], 'Commit', 'کامیت کردن', 'Закоммитить'],
  [
    'local',
    'amend',
    'local',
    'write',
    [],
    ['body'],
    'Amend the last commit',
    'اصلاح کامیت آخر',
    'Исправить последний коммит',
  ],
  ['local', 'push', 'local', 'write', [], ['branch', 'force'], 'Push', 'پوش کردن', 'Запушить'],
  ['local', 'pull', 'local', 'write', [], ['branch'], 'Pull', 'پول کردن', 'Подтянуть изменения'],
  ['local', 'fetch', 'local', 'read', [], [], 'Fetch', 'فچ کردن', 'Получить изменения'],
  [
    'local',
    'merge',
    'local',
    'write',
    ['branch'],
    ['base'],
    'Merge a branch here',
    'مرج برنچ',
    'Слить ветку',
  ],
  [
    'local',
    'rebase',
    'local',
    'write',
    ['branch'],
    [],
    'Rebase onto a branch',
    'ری‌بیس',
    'Перебазировать',
  ],
  [
    'local',
    'stash',
    'local',
    'write',
    [],
    ['body'],
    'Stash the changes',
    'استش کردن',
    'Спрятать изменения',
  ],
  [
    'local',
    'unstash',
    'local',
    'write',
    [],
    [],
    'Bring the stash back',
    'برگرداندن استش',
    'Вернуть спрятанное',
  ],
  [
    'local',
    'reset',
    'local',
    'destructive',
    [],
    ['ref', 'force'],
    'Reset',
    'ریست کردن',
    'Сбросить',
  ],
  [
    'local',
    'discard',
    'local',
    'destructive',
    [],
    ['path'],
    'Throw changes away',
    'دور ریختن تغییرات',
    'Отменить изменения',
  ],
  [
    'local',
    'cherry-pick',
    'local',
    'write',
    ['ref'],
    [],
    'Cherry-pick a commit',
    'چری‌پیک',
    'Черри-пик',
  ],
  [
    'local',
    'revert',
    'local',
    'write',
    ['ref'],
    [],
    'Revert a commit',
    'ریورت کامیت',
    'Откатить коммит',
  ],
  [
    'local',
    'init',
    'local',
    'write',
    [],
    ['path'],
    'Make a repository here',
    'گیت اینیت',
    'Инициализировать репозиторий',
  ],
  [
    'local',
    'remote-add',
    'local',
    'write',
    ['url'],
    ['title'],
    'Add a remote',
    'افزودن ریموت',
    'Добавить remote',
  ],
];

export const GIT_ACTIONS: readonly GitAction[] = ROWS.map(
  ([object, verb, scope, weight, needs, takes, en, fa, ru]) => ({
    id: `${object}.${verb}`,
    object,
    verb,
    scope,
    weight,
    needs,
    takes,
    en,
    fa,
    ru,
  }),
);

const BY_ID = new Map(GIT_ACTIONS.map((a) => [a.id, a]));

export function gitAction(id: string): GitAction | undefined {
  return BY_ID.get(id);
}

/** Whether a verb can be done to an object at all: the pairs the model may answer with. */
export function pairOf(object: GitObject, verb: GitVerb): GitAction | undefined {
  return BY_ID.get(`${object}.${verb}`);
}
