/**
 * How git is said, language by language: the words for each verb and each object of
 * actions.ts, and the little words around them -- who an issue goes to, which repository, from
 * which branch to which.
 *
 * One entry per language. A word here is a STEM, matched at the start of a word ("close" finds
 * "closed", "закр" finds "закройте", "ببند" finds "ببندش"); a stem with a space in it is a phrase.
 * Chinese and Japanese have no spaces, so theirs are matched anywhere in the line. Lowercase,
 * and Persian with its Arabic letters already folded (text.ts).
 *
 * The model (model.ts) does not depend on this list being complete -- it learns from letters as
 * well -- but every word here is one it can be sure of, and the slot readers (slots.ts) need the
 * little words to find a person, a repository or a branch whatever order the sentence is in.
 */

import type { GitObject, GitVerb } from '@core/box/git/actions.ts';
import { fold } from '@core/box/text.ts';

export interface GitSpeech {
  lang: string;
  /** No spaces between words: matched inside the line. */
  dense?: boolean;
  verbs: Partial<Record<GitVerb, string[]>>;
  objects: Record<GitObject, string[]>;
  /** Before a person an issue is given to: "to sina", "به سینا", "на сину". */
  toPerson: string[];
  /** Before a repository: "in web", "توی web", "в web". */
  inRepo: string[];
  /** Branch from and to: "from fix into main", "از fix به main", "из fix в main". */
  from: string[];
  into: string[];
  /** Said of oneself: "my issues", "assigned to me". */
  mine: string[];
  /** States a list is asked for in. */
  open: string[];
  closed: string[];
  merged: string[];
  all: string[];
  /** On the service rather than here, and here rather than on the service. */
  remoteCue: string[];
  localCue: string[];
  /** Before a label's name: "label bug", "لیبل باگ". */
  labelWord: string[];
  /** Words that are about the thing just talked about: "it", "that one", "همون". */
  that: string[];
}

export const GIT_SPEECH: readonly GitSpeech[] = [
  {
    lang: 'en',
    verbs: {
      create: [
        'create',
        'make',
        'new ',
        'add ',
        'file ',
        'raise',
        'report',
        'log ',
        'submit',
        'start a',
        'write up',
        'put up',
        'cut a',
        'set up',
        'spin up',
        'draft',
      ],
      list: [
        'last ',
        'latest ',
        'list',
        'show all',
        'show me all',
        'what are',
        'which ',
        'any open',
        'all open',
        'all my',
        'my open',
        'pending',
        'outstanding',
        'ls ',
      ],
      show: [
        'what does it say',
        'say again',
        'show me that',
        'show',
        'view',
        'see ',
        'display',
        'look at',
        'details',
        'describe',
        "what's in",
        'what is in',
        'tell me about',
        'pull up',
        'fetch issue',
        'get issue',
      ],
      close: [
        'kill',
        'decline',
        'abandon',
        'drop the pr',
        'reject the',
        'close',
        'shut',
        'resolve',
        'mark as done',
        'mark as fixed',
        'mark done',
        'mark fixed',
        "won't fix",
        'wontfix',
      ],
      reopen: [
        'bring it back',
        'bring back pull',
        'we need it after all',
        'reopen',
        're-open',
        'open again',
        'open back',
        'bring back',
        'revive',
        'undo close',
      ],
      comment: [
        "write '",
        "write '",
        'write on it',
        'post a comment',
        'comment',
        'reply',
        'respond',
        'answer',
        'leave a note',
        'leave a comment',
        'write on',
        'say on',
        'tell them',
        'post on',
        'note on',
        'add a comment',
      ],
      assign: ['assign', 'give ', 'hand ', 'hand over', 'delegate', 'put on', 'take ', 'owner'],
      unassign: ['unassign', 'take off', 'remove assignee', 'drop assignee', 'unset owner'],
      label: ['label', 'tag as', 'mark as', 'add label', 'add the label', 'categorize'],
      unlabel: [
        'unlabel',
        'remove label',
        'remove the label',
        'drop label',
        'drop the label',
        'untag',
        'take the label',
      ],
      edit: [
        'edit',
        'rename',
        'retitle',
        'change the title',
        'change title',
        'update the description',
        'update description',
        'change the description',
        'reword',
        'update the body',
        'fix the title',
      ],
      milestone: ['milestone', 'move to milestone', 'put in milestone', 'target ', 'schedule for'],
      lock: ['stop comments', 'close the conversation', 'lock'],
      unlock: ['let people comment', 'open the conversation', 'unlock'],
      diff: [
        'touch',
        'touches',
        'what files does',
        'diff',
        'files changed',
        'changed files',
        'what changed in',
        'what does',
        'changes in',
        'what files',
      ],
      merge: ['merge', 'land', 'squash and merge', 'squash-merge', 'rebase and merge', 'ship '],
      approve: ['approve', 'lgtm', 'sign off', 'looks good', 'accept'],
      'request-changes': [
        'request changes',
        'needs changes',
        'needs work',
        'request a change',
        'ask for changes',
        'reject',
      ],
      'request-review': [
        'ask for review',
        'and ask',
        'request review',
        'request a review',
        'ask for a review',
        'review from',
        'to review',
        'get a review',
        'ask review',
        'add reviewer',
        'reviewer',
      ],
      ready: [
        'ready for review',
        'mark ready',
        'mark as ready',
        'undraft',
        'out of draft',
        'no longer a draft',
        'not a draft',
      ],
      checkout: ['check out', 'checkout', 'try locally', 'test locally', 'pull down'],
      delete: [
        'delete',
        'remove',
        'drop ',
        'get rid of',
        'destroy',
        'nuke',
        'rm ',
        'erase',
        'kill the',
      ],
      switch: [
        'switch',
        'checkout',
        'check out',
        'go to',
        'move to',
        'jump to',
        'change to',
        'go on',
      ],
      rename: ['rename', 'call it'],
      compare: [
        "that isn't in",
        'that is not in',
        'not in',
        'compare',
        'difference between',
        'diff between',
        'ahead of',
        'behind',
        'how far',
      ],
      status: [
        'which files did i',
        'what did i touch',
        'what files did i',
        'status',
        'pass',
        'passing',
        'green',
        'red',
        'failing',
        'failed',
        'broken',
        'state of',
        'did the build',
        'is the build',
        'how is ci',
        'how is the build',
        'checks',
      ],
      rerun: [
        'rerun',
        're-run',
        'retry',
        'restart',
        'run again',
        'trigger',
        'kick off',
        'rebuild',
        'run the',
      ],
      cancel: ['cancel', 'stop', 'abort', 'kill'],
      fork: ['fork'],
      star: ['star ', 'star the', 'favorite', 'give a star', 'like the repo'],
      unstar: ['unstar', 'remove star', 'remove my star', 'take back my star'],
      clone: ['clone', 'download the repo', 'get a copy', 'git clone'],
      search: ['search', 'find', 'grep', 'where is', 'look for', 'which file'],
      read: ['mark as read', 'mark read', 'mark all read', 'clear', 'dismiss'],
      connect: [
        'log in to',
        'login to',
        'sign into',
        'connect',
        'link my',
        'sign in',
        'log in',
        'login',
        'add my account',
        'add a token',
        'hook up',
      ],
      disconnect: [
        'disconnect',
        'unlink',
        'sign out of',
        'log out of',
        'remove my account',
        'forget',
      ],
      whoami: [
        'who am i',
        'which account',
        'what account',
        'logged in as',
        'signed in as',
        'whoami',
      ],
      stage: [
        'stage',
        'git add',
        'add all',
        'add the changes',
        'add everything',
        'add the file',
        'add file',
      ],
      unstage: ['unstage', 'remove from staging', 'reset head'],
      commit: [
        'commit with message',
        'commit with the message',
        'commit',
        'check in',
        'save the changes as',
        'save changes as',
      ],
      amend: ['amend', 'fix the last commit', 'change the last commit', 'edit the last commit'],
      push: ['push', 'publish the branch', 'send it up', 'upload my'],
      pull: ['pull', 'sync', 'get the latest', 'update from', 'bring in the latest'],
      fetch: ["but don't merge", 'without merging', 'fetch'],
      rebase: ['rebase'],
      stash: ['stash', 'shelve', 'set aside', 'put away my'],
      unstash: [
        'stash apply',
        'apply my stash',
        'unstash',
        'stash pop',
        'pop the stash',
        'apply the stash',
        'bring back my',
        'restore the stash',
      ],
      reset: ['reset', 'go back to', 'roll back', 'undo the last', 'undo my last'],
      discard: [
        'uncommitted edits',
        'throw out my',
        'wipe my changes',
        'get rid of all my',
        'discard',
        'throw away',
        'drop my changes',
        'restore',
        'undo my changes',
        'undo changes',
        'revert my changes',
        'revert changes',
        'get rid of my changes',
      ],
      'cherry-pick': ['cherry-pick', 'cherry pick', 'cherrypick', 'pick commit'],
      revert: ['revert', 'undo commit', 'back out'],
      blame: ['blame', 'who wrote', 'who changed', 'who touched'],
      init: [
        'init',
        'initialize',
        'initialise',
        'make this a repo',
        'make this folder a repo',
        'start a repo here',
      ],
      'remote-add': [
        'add remote',
        'add a remote',
        'add origin',
        'set origin',
        'set the remote',
        'add an origin',
      ],
    },
    objects: {
      issue: [
        'issue',
        'bug',
        'ticket',
        'task',
        'work item',
        'problem',
        'feature request',
        'incident',
      ],
      pr: [
        'pr',
        'prs',
        'pull request',
        'pull-request',
        'merge request',
        'mr',
        'mrs',
        'patch',
        'draft',
      ],
      branch: ['branch', 'branches'],
      commit: ['commit', 'commits', 'history', 'log', 'sha', 'changeset'],
      ci: [
        'ci',
        'build',
        'pipeline',
        'checks',
        'actions',
        'workflow',
        'tests',
        'job',
        'run',
        'deploy',
      ],
      release: ['release', 'releases', 'changelog'],
      tag: ['tag', 'tags'],
      label: ['label', 'labels'],
      milestone: ['milestone', 'milestones', 'sprint'],
      repo: ['repo', 'repository', 'repositories', 'project', 'projects'],
      file: ['file', 'readme', 'line', 'contents of'],
      code: ['code', 'codebase', 'source'],
      member: [
        'member',
        'collaborator',
        'contributor',
        'maintainer',
        'team',
        'people',
        'who works',
      ],
      notification: ['notification', 'inbox', 'mention', 'pings', 'alerts'],
      account: ['account', 'token', 'github', 'gitlab', 'gitea', 'login', 'access'],
      local: [
        'changes',
        'working tree',
        'working copy',
        'staged',
        'unstaged',
        'stash',
        'remote',
        'origin',
        'upstream',
        'local',
        'workspace',
        'my work',
        'this folder',
        'uncommitted',
      ],
    },
    toPerson: ['to', 'for', 'onto', 'on'],
    inRepo: ['in', 'on', 'for', 'at', 'from', 'of', 'under', 'into'],
    from: ['from'],
    into: ['into', 'to', 'onto', 'against', 'on top of'],
    mine: [
      'my ',
      'mine',
      'assigned to me',
      'for me',
      "i'm on",
      'i am on',
      'i opened',
      'i made',
      'i wrote',
      'i created',
    ],
    open: ['open', 'active', 'pending', 'outstanding', 'unresolved'],
    closed: ['closed', 'resolved', 'done', 'finished'],
    merged: ['merged', 'landed'],
    all: ['all states', 'every', 'open and closed', 'including closed'],
    remoteCue: [
      'on github',
      'on gitlab',
      'on gitea',
      'on the server',
      'on origin',
      'upstream',
      'remote',
    ],
    localCue: [
      'locally',
      'local',
      'here',
      'on my machine',
      'this folder',
      'in this repo',
      'my laptop',
    ],
    labelWord: ['label', 'labels', 'tag', 'tagged', 'labelled', 'labeled'],
    that: [
      'that commit',
      'that pr',
      'that issue',
      'that branch',
      'this pr',
      'this issue',
      'the one',
      'it',
      'that',
      'that one',
      'this one',
      'the same',
      'the last one',
      'same one',
    ],
  },
  {
    lang: 'fa',
    verbs: {
      create: [
        'بساز',
        'ساختن',
        'بسازی',
        'بسازید',
        'درست کن',
        'درست کنید',
        'ثبت کن',
        'ثبت کنید',
        'ثبت شه',
        'بزن',
        'بزنید',
        'باز کن',
        'یه ایشو',
        'جدید',
        'تازه',
        'اضافه کن',
        'ایجاد',
        'بنویس',
        'گزارش',
        'ریپورت',
        'کریت',
        'بازش کن',
      ],
      list: [
        'اخیر',
        'این اواخر',
        'لیست',
        'فهرست',
        'همه',
        'کدوما',
        'کدام',
        'چیا',
        'چه ایشو',
        'چه پی ار',
        'چندتا',
        'چند تا',
        'نشون بده',
        'نشان بده',
        'بیار',
        'ببینم',
        'باز های',
        'های باز',
        'ای باز',
      ],
      show: [
        'بیار ببینم',
        'نشونم بده',
        'نشون بده ببینم',
        'اطلاعات',
        'مشخصات',
        'رو ببینم',
        'نشون بده',
        'نشان بده',
        'ببینم',
        'بیار',
        'جزئیات',
        'جزییات',
        'چی نوشته',
        'چیه',
        'باز کن ببینم',
        'نمایش',
      ],
      close: [
        'ببند',
        'بستن',
        'بسته کن',
        'بسته شه',
        'ببندیم',
        'ببندید',
        'تموم شد',
        'حل شد',
        'حلش',
        'ریزالو',
        'کلوز',
      ],
      reopen: [
        'دوباره باز',
        'بازش کن دوباره',
        'از نو باز',
        'ری اوپن',
        'برگردون',
        'باز کن دوباره',
        'مجدد باز',
      ],
      comment: [
        'کامنت',
        'نظر',
        'جواب بده',
        'جواب بنویس',
        'بنویس زیر',
        'زیرش بنویس',
        'پاسخ',
        'بگو',
        'یادداشت بذار',
      ],
      assign: [
        'بدش به',
        'بده ش به',
        'اساینش',
        'بنداز به اسم',
        'بسپرش',
        'اساین',
        'بده به',
        'بسپار',
        'واگذار',
        'بنداز گردن',
        'به عهده',
        'مسئول',
        'بده دست',
      ],
      unassign: [
        'برش دار',
        'برداری',
        'دیگه مسئول',
        'مسئول نیست',
        'از اساین در',
        'آن اساین',
        'اناساین',
        'بردار',
        'از گردن',
        'مسئولشو بردار',
        'از روی',
      ],
      label: [
        'بهش بزن',
        'روش بزن',
        'لیبل بزن',
        'برچسب بزن',
        'لیبل',
        'برچسب',
        'تگ کن',
        'بزن روش',
        'علامت بزن',
      ],
      unlabel: [
        'لیبل رو پاک',
        'لیبلو پاک',
        'برچسبو پاک',
        'اون لیبل',
        'لیبلشو پاک',
        'لیبل رو بردار',
        'لیبلشو بردار',
        'برچسب رو بردار',
        'برچسبشو بردار',
        'لیبل حذف',
        'حذف لیبل',
        'برچسب حذف',
      ],
      edit: [
        'عنوانشو بکن',
        'عنوانش رو بکن',
        'اسمشو بکن',
        'عنوان رو بکن',
        'تیترشو',
        'ویرایش',
        'ادیت',
        'عوض کن',
        'تغییر بده',
        'اسمشو',
        'عنوانشو',
        'عنوان رو',
        'توضیحاتشو',
        'آپدیت کن',
        'به روز کن',
        'بروز کن',
        'اصلاح کن',
      ],
      milestone: [
        'بذارش تو مایلستون',
        'ببرش تو مایلستون',
        'تو مایلستون',
        'مایلستون',
        'مایل استون',
        'نقطه عطف',
        'اسپرینت',
      ],
      lock: ['کامنتا رو ببند', 'بحث رو ببند', 'قفل کن', 'قفلش'],
      unlock: ['دوباره بتونن کامنت', 'قفلشو بردار', 'قفلشو باز', 'قفل رو باز', 'از قفل'],
      diff: ['دیف', 'تغییرات', 'چی عوض', 'چه فایل', 'فایلای عوض', 'چیا تغییر'],
      merge: [
        'بیار تو برنچ',
        'بریز تو',
        'مرج کن تو',
        'مرج',
        'ادغام',
        'مرجش',
        'بچسبون به',
        'یکی کن',
        'لند کن',
      ],
      approve: ['اپروو', 'اپرو', 'تایید', 'تأیید', 'قبول', 'اوکی بده', 'اوکیش کن', 'ال جی تی ام'],
      'request-changes': [
        'تغییرات بخواه',
        'تغییر بخواه',
        'درخواست تغییرات',
        'درخواست تغییر',
        'تغییر بخواه',
        'ریکوئست چنج',
        'رد کن',
        'برگشت بزن',
        'نیاز به تغییر',
      ],
      'request-review': [
        'یه نگاه بندازه',
        'نگاه بندازه',
        'ریویور اضافه',
        'ریویوور',
        'ریویو',
        'بازبینی',
        'بررسی کنه',
        'بررسی کنن',
        'نگاه کنه',
        'ریویوئر',
      ],
      ready: ['آماده ریویو', 'آماده بررسی', 'از درفت', 'از حالت پیش نویس', 'ردی کن', 'آمادش کن'],
      checkout: [
        'بیارش رو لوکال',
        'رو لوکال',
        'بیار رو سیستمم',
        'چک اوت',
        'چک‌اوت',
        'لوکال',
        'رو سیستمم',
        'بیارش رو',
        'تست کنم',
      ],
      delete: [
        'حذف',
        'پاک کن',
        'پاکش',
        'بپاک',
        'دیلیت',
        'از بین ببر',
        'بنداز دور',
        'پاک شه',
        'حذفش',
      ],
      switch: [
        'منو ببر رو',
        'ببر رو برنچ',
        'برو تو برنچ',
        'سویچ کن',
        'سوییچ کن',
        'برو رو',
        'برو به',
        'سوییچ',
        'سویچ',
        'چک اوت',
        'عوض کن به',
        'بپر رو',
        'منتقل شو',
      ],
      rename: [
        'ریناین',
        'رینیم کن',
        'اسمشو عوض',
        'تغییر نام',
        'اسمشو بذار',
        'اسمش رو بذار',
        'رینیم',
        'اسم برنچ',
      ],
      compare: [
        'تو اون نیست',
        'که تو',
        'مقایسه',
        'فرق',
        'تفاوت',
        'چقدر جلوئه',
        'جلوتره',
        'عقب تره',
        'کامپیر',
      ],
      status: [
        'وضعیت',
        'پاس شد',
        'پاس شده',
        'رد شد',
        'فیل شد',
        'فیل شده',
        'سبزه',
        'قرمزه',
        'خراب شد',
        'چی شد',
        'رد شده',
        'گذشت',
        'اوکیه',
        'درسته',
      ],
      rerun: [
        'دوباره اجرا',
        'دوباره ران',
        'ری ران',
        'از اول اجرا',
        'مجدد اجرا',
        'دوباره بزن',
        'ریستارت',
        'دوباره راه بنداز',
        'تریگر',
      ],
      cancel: ['کنسل', 'لغو', 'متوقف کن', 'وایسون', 'استاپ'],
      fork: ['فورک'],
      star: ['ستاره بده', 'ستاره بزن', 'استار کن', 'ستاره کن'],
      unstar: [
        'پس بگیر',
        'ستاره ام رو',
        'ستارمو',
        'ستاره رو بردار',
        'ستارشو بردار',
        'آن استار',
        'استارشو بردار',
      ],
      clone: ['کلون', 'کلن کن', 'دانلود کن ریپو', 'بگیرش رو سیستم'],
      search: [
        'کجاها',
        'کجای کد',
        'کجاهای',
        'جستجو',
        'جست و جو',
        'بگرد',
        'پیدا کن',
        'کجاست',
        'کجا نوشته',
      ],
      read: [
        'بزن خونده',
        'خونده شد',
        'خوانده شد',
        'سین شده',
        'خونده شده',
        'خوانده شده',
        'خوندم',
        'پاکشون کن',
        'سین کن',
      ],
      connect: ['وصل کن', 'وصل شو', 'اتصال', 'لاگین', 'وارد شو', 'توکن', 'کانکت'],
      disconnect: [
        'لاگ اوت',
        'لاگ‌اوت',
        'خارج شو',
        'ساین اوت',
        'قطع کن',
        'قطعش',
        'دیسکانکت',
        'جدا کن',
        'خارج شو از',
      ],
      whoami: [
        'کی ام من',
        'کی هستم',
        'من کی ام',
        'با چه اکانتی',
        'با چه حسابی',
        'کدوم حساب',
        'من کیم',
        'با کی وصلم',
        'به چه اکانتی',
      ],
      stage: [
        'بذار تو کامیت بعدی',
        'بذار تو استیج',
        'اضافه کن به کامیت بعدی',
        'استیج',
        'اد کن',
        'add کن',
        'اضافه کن به استیج',
        'گیت اد',
      ],
      unstage: ['آن‌استیج', 'آناستیج', 'از استیج در', 'آن استیج', 'از استیج', 'انستیج'],
      commit: [
        'یه کامیت بزن',
        'کامیت بزن',
        'کامیتش کن',
        'کامیت',
        'کامیتش',
        'کمیت',
        'ثبت کن تغییرات',
        'کامیت کن',
      ],
      amend: ['امند', 'کامیت آخر رو اصلاح', 'کامیت قبلی رو درست', 'پیام کامیت آخر'],
      push: [
        'بفرست رو',
        'بفرست به',
        'بفرستش',
        'پوشش بده',
        'پوش بده',
        'پوش',
        'پوشش کن',
        'بفرست بالا',
        'بفرست رو سرور',
        'آپلود کن',
      ],
      pull: [
        'پول کن',
        'پولش کن',
        'آخرین تغییرات',
        'سینک کن',
        'به روز کن از',
        'بکش پایین',
        'پول بگیر',
      ],
      fetch: ['فچ کن', 'ولی مرج نکن', 'مرج نکن', 'فچ'],
      rebase: ['ریبیس', 'ری بیس', 'ری‌بیس'],
      stash: ['استش', 'کنار بذار', 'نگه دار تغییرات'],
      unstash: [
        'استش شده رو',
        'استش‌شده',
        'اپلای',
        'استش رو بیار',
        'استش پاپ',
        'استش رو برگردون',
        'برگردون استش',
        'پاپ کن',
        'از استش',
      ],
      reset: [
        'کامیت آخر رو برگردون',
        'ولی تغییرات بمونه',
        'آخرین کامیت رو برگردون',
        'آندو کن کامیت',
        'ریست',
        'برگرد به',
        'برگردون به',
        'رول بک',
      ],
      discard: [
        'هرچی کامیت نکردم',
        'هر چی کامیت نکردم',
        'تغییراتمو پاک',
        'تغییرات کامیت نشده رو پاک',
        'دور بریز',
        'بیخیال تغییرات',
        'تغییرات رو پاک',
        'ریستور',
        'برگردون تغییرات',
        'دیسکارد',
      ],
      'cherry-pick': ['چری پیک', 'چری‌پیک', 'چریپیک'],
      revert: ['ریورت', 'برگردون کامیت', 'کامیت رو برگردون', 'خنثی کن'],
      blame: ['بلیم', 'کی نوشته', 'کی عوض کرده', 'کار کیه'],
      init: ['اینیت', 'init', 'ریپو کن', 'گیت راه بنداز', 'گیتی کن'],
      'remote-add': ['ریموت اضافه', 'اضافه کن ریموت', 'اوریجین رو بذار', 'ریموت بذار', 'ریموت ست'],
    },
    objects: {
      issue: ['ایشو', 'ایشیو', 'باگ', 'تیکت', 'تسک', 'مشکل', 'مسئله', 'ورک آیتم'],
      pr: [
        'پول ریکوئست',
        'پولریکوئستو',
        'پی ار',
        'پی‌ار',
        'پول ریکوئست',
        'پول‌ریکوئست',
        'پولریکوئست',
        'درخواست ادغام',
        'مرج ریکوئست',
        'ام ار',
        'pr',
        'mr',
      ],
      branch: ['برنچ', 'برانچ', 'شاخه', 'برنچا'],
      commit: ['کامیت', 'کمیت', 'تاریخچه', 'لاگ', 'هیستوری'],
      ci: [
        'سی آی',
        'ci',
        'بیلد',
        'پایپ لاین',
        'پایپلاین',
        'اکشن',
        'تست ها',
        'تستا',
        'جاب',
        'ورکفلو',
        'دیپلوی',
      ],
      release: ['ریلیز', 'انتشار', 'نسخه'],
      tag: ['تگ'],
      label: ['لیبل', 'برچسب'],
      milestone: ['مایلستون', 'مایل استون', 'اسپرینت'],
      repo: ['ریپو', 'مخزن', 'پروژه', 'ریپازیتوری', 'رپو'],
      file: ['فایل', 'ریدمی', 'readme', 'خط'],
      code: ['کد', 'سورس'],
      member: ['اعضا', 'عضو', 'همکار', 'کانتریبیوتر', 'کیا رو', 'تیم'],
      notification: ['نوتیف', 'اعلان', 'نوتیفیکیشن', 'منشن'],
      account: ['حساب', 'اکانت', 'گیت هاب', 'گیتهاب', 'گیت لب', 'گیتلب', 'گیتی', 'توکن'],
      local: [
        'تغییرات',
        'تغییراتم',
        'لوکال',
        'استش',
        'ریموت',
        'اوریجین',
        'رو سیستمم',
        'همینجا',
        'فولدر',
      ],
    },
    toPerson: ['به', 'بده به', 'واسه', 'برای'],
    inRepo: ['در', 'توی', 'تو', 'روی', 'رو', 'واسه', 'برای', 'از', 'ریپوی', 'پروژه ی'],
    from: ['از'],
    into: ['به', 'تو', 'توی', 'روی', 'رو'],
    mine: ['من', 'خودم', 'مال من', 'به من', 'برای من', 'ـم'],
    open: ['باز', 'فعال', 'اوپن'],
    closed: ['بسته', 'حل شده', 'تموم شده', 'کلوز'],
    merged: ['مرج شده', 'ادغام شده'],
    all: ['همه', 'باز و بسته', 'همشون'],
    remoteCue: ['روی گیت هاب', 'رو گیت هاب', 'روی گیتهاب', 'روی گیت لب', 'روی سرور', 'ریموت'],
    localCue: ['لوکال', 'رو سیستمم', 'روی سیستمم', 'همینجا', 'این فولدر', 'لپ تاپم', 'محلی'],
    labelWord: ['لیبل', 'برچسب', 'تگ'],
    that: [
      'مرجش',
      'بازش',
      'اساینش',
      'بدش',
      'ببرش',
      'بذارش',
      'بیارش',
      'کامیتش',
      'پاکش',
      'حذفش',
      'تاییدش',
      'اپرووش',
      'لیبلش',
      'ریویوش',
      'بهش',
      'روش',
      'ازش',
      'اون پی ار',
      'اون ایشو',
      'اون کامیت',
      'اون برنچ',
      'همونو',
      'همون',
      'همین',
      'اینو',
      'اونو',
      'اون یکی',
      'این یکی',
      'ببندش',
      'مرجش',
      'بازش',
    ],
  },
  {
    lang: 'ru',
    verbs: {
      create: [
        'созда',
        'сдела',
        'заведи',
        'завести',
        'открой',
        'нов',
        'добав',
        'оформ',
        'напиши',
        'зареги',
        'запили',
        'поставь задачу',
      ],
      list: [
        'список',
        'какие у меня',
        'покажи мои',
        'список',
        'покажи все',
        'какие',
        'все открытые',
        'что открыто',
        'сколько',
        'выведи',
        'перечисли',
        'мои',
      ],
      show: ['покажи', 'посмотр', 'открой', 'что в', 'подробн', 'детали', 'глянь', 'выведи'],
      close: [
        'закрывай',
        'не нужен',
        'не нужна',
        'закр',
        'закро',
        'реши',
        'отметь как готов',
        'готово',
      ],
      reopen: [
        'открой обратно',
        'обратно открой',
        'верни обратно',
        'переоткр',
        'открой снова',
        'открой заново',
        'снова открой',
        'верни',
      ],
      comment: ['коммент', 'ответь', 'напиши в', 'напиши под', 'отпиши', 'прокоммент', 'оставь'],
      assign: ['назнач', 'отдай', 'повесь на', 'передай', 'поручи', 'на себя'],
      unassign: ['сними', 'убери с', 'сними назначение', 'отвяжи'],
      label: [
        'добавь метку',
        'метку добавь',
        'метк',
        'пометь',
        'лейбл',
        'ярлык',
        'повесь метку',
        'добавь метку',
      ],
      unlabel: ['убери метку', 'сними метку', 'удали метку', 'убери лейбл'],
      edit: [
        'перекрас',
        'смени цвет',
        'измени',
        'поменяй',
        'переименуй',
        'отредактир',
        'обнови описание',
        'исправь заголовок',
        'обнови заголовок',
      ],
      milestone: ['вех', 'майлстоун', 'милстоун', 'спринт'],
      lock: ['залочь', 'залочи', 'заблокир', 'запри'],
      unlock: ['разлочь', 'разлочи', 'разблокируй', 'разблокир'],
      diff: ['дифф', 'диф', 'дифф', 'диф', 'изменения в', 'что поменял', 'какие файлы'],
      merge: ['смерж', 'смёрж', 'мерж', 'мёрж', 'слей', 'слить', 'влей', 'вмерж'],
      approve: ['апрув', 'одобр', 'аппрув', 'заапрув', 'лгтм', 'прими'],
      'request-changes': [
        'запроси изменения',
        'нужны правки',
        'на доработку',
        'отклони',
        'верни на доработку',
      ],
      'request-review': ['ревью', 'посмотрел', 'проверил', 'ревьюер', 'на проверку'],
      ready: ['готов к ревью', 'из черновика', 'сними черновик', 'отметь готовым'],
      checkout: ['чекаут', 'локально', 'вытяни', 'стяни себе'],
      delete: [
        'снес',
        'снести',
        'грохн',
        'удали',
        'удалить',
        'снеси',
        'грохни',
        'убери',
        'стереть',
        'сотри',
      ],
      switch: [
        'свитчн',
        'свитч',
        'свичн',
        'переключ',
        'перейди',
        'чекаут',
        'зайди на',
        'встань на',
      ],
      rename: ['переименуй', 'переименовать'],
      compare: ['сравни', 'разница между', 'насколько отстает', 'опережает', 'отстает'],
      status: [
        'статус',
        'прош',
        'зелен',
        'красн',
        'упал',
        'упала',
        'сломал',
        'как там',
        'что с',
        'проходят',
        'прошли',
      ],
      rerun: [
        'рестарт',
        'перезапуст',
        'перезапус',
        'запусти снова',
        'запусти еще',
        'прогони',
        'ретрай',
        'еще раз',
      ],
      cancel: ['отмен', 'останови', 'прерви', 'стопни'],
      fork: ['форкни', 'форк'],
      star: ['звезд', 'поставь звезду', 'застарь'],
      unstar: ['убери звезду', 'сними звезду'],
      clone: ['клонир', 'склонируй', 'клонируй'],
      search: ['поиск', 'найди', 'ищи', 'где в коде', 'где лежит', 'грепни'],
      read: ['прочитай', 'прочти', 'прочитан', 'отметь прочитан', 'очисти'],
      connect: ['подключ', 'привяж', 'залогин', 'войди', 'токен'],
      disconnect: ['отключ', 'отвяж', 'выйди из'],
      whoami: ['кто я', 'под кем', 'какой аккаунт', 'под каким'],
      stage: [
        'добавь в индекс',
        'застейдж',
        'стейдж',
        'гит адд',
        'git add',
        'добавь все',
        'добавь изменения',
      ],
      unstage: ['убери из индекса', 'анстейдж'],
      commit: ['закоммит', 'коммитни', 'сделай коммит', 'коммит с'],
      amend: ['аменд', 'поправь последний коммит', 'исправь последний коммит'],
      push: ['запуш', 'пушни', 'пуш', 'отправь на сервер', 'залей'],
      pull: [
        'спуль',
        'пульни',
        'спулл',
        'пулл',
        'спулл',
        'подтяни',
        'стяни',
        'обнови с',
        'синхрониз',
      ],
      fetch: ['фетч', 'зафетч'],
      rebase: ['ребейз', 'перебазир', 'ребазни'],
      stash: ['застэш', 'стэш', 'застеш', 'стеш', 'спрячь', 'отложи изменения', 'застеш'],
      unstash: ['верни стеш', 'стеш поп', 'достань из стеша', 'примени стеш'],
      reset: ['ресет', 'сбрось', 'откатись', 'откати на'],
      discard: [
        'локальные изменения',
        'все изменения откати',
        'откати все',
        'выкинь изменения',
        'отмени изменения',
        'сбрось изменения',
        'восстанови файл',
        'откати изменения',
      ],
      'cherry-pick': ['черри', 'чери-пик', 'черрипик'],
      revert: ['ревертни', 'реверт', 'откати коммит', 'отмени коммит'],
      blame: ['блейм', 'кто написал', 'кто менял', 'кто изменил'],
      init: ['инициализ', 'init', 'сделай репозиторий тут'],
      'remote-add': [
        'добавь remote',
        'добавь ремоут',
        'добавь origin',
        'пропиши origin',
        'добавь удаленный',
      ],
    },
    objects: {
      issue: ['задач', 'issue', 'ишью', 'иссью', 'баг', 'тикет', 'ошибк', 'проблем'],
      pr: [
        'пр',
        'пул-реквест',
        'пулл-реквест',
        'пул реквест',
        'пулл реквест',
        'мерж-реквест',
        'мердж-реквест',
        'мерж реквест',
        'mr',
        'pr',
        'реквест',
      ],
      branch: ['ветк', 'ветв', 'бранч'],
      commit: ['коммит', 'истори', 'лог'],
      ci: [
        'ci',
        'си-ай',
        'сборк',
        'билд',
        'пайплайн',
        'тесты',
        'джоб',
        'экшен',
        'деплой',
        'проверки',
      ],
      release: ['релиз'],
      tag: ['тег'],
      label: ['метк', 'лейбл', 'ярлык'],
      milestone: ['вех', 'майлстоун', 'милстоун', 'спринт'],
      repo: ['реп', 'репа', 'репу', 'репы', 'репо', 'репозитори', 'проект'],
      file: ['файл', 'readme', 'ридми', 'строк'],
      code: ['код', 'исходник'],
      member: ['участник', 'коллаборатор', 'команд', 'кто работает'],
      notification: ['уведомлени', 'уведомлен', 'нотификац', 'упоминани'],
      account: ['аккаунт', 'учетк', 'токен', 'github', 'gitlab', 'gitea', 'гитхаб', 'гитлаб'],
      local: [
        'изменения',
        'локальн',
        'стеш',
        'remote',
        'origin',
        'ремоут',
        'рабочей копии',
        'тут',
        'здесь',
      ],
    },
    toPerson: ['на', 'для', 'к'],
    inRepo: ['в', 'во', 'на', 'для', 'из', 'по'],
    from: ['из', 'от', 'с'],
    into: ['в', 'во', 'на'],
    mine: ['мои', 'моих', 'мой', 'мне', 'на мне', 'на меня', 'я открыл', 'я создал'],
    open: ['открыт', 'активн'],
    closed: ['закрыт', 'решенн'],
    merged: ['смерженн', 'слит', 'влит'],
    all: ['все', 'всех', 'включая закрытые'],
    remoteCue: ['на гитхабе', 'на github', 'на гитлабе', 'на сервере', 'на origin', 'удаленн'],
    localCue: ['локально', 'тут', 'здесь', 'у меня', 'в этой папке'],
    labelWord: ['метк', 'лейбл', 'ярлык'],
    that: [
      'его',
      'её',
      'ее',
      'этот',
      'эту',
      'этой',
      'этого',
      'тот же',
      'его',
      'ее',
      'её',
      'этот',
      'эту',
      'тот',
      'ту',
      'тоже',
    ],
  },
  ...(
    [
      [
        'de',
        {
          create: ['erstelle', 'neues', 'neuer', 'neue', 'lege', 'melde', 'mach'],
          list: ['zeig alle', 'liste', 'welche', 'meine', 'offene'],
          show: ['zeig', 'zeige'],
          close: ['schließ', 'schliess', 'erledigt'],
          reopen: ['wieder öffnen', 'öffne wieder', 'erneut öffnen'],
          comment: ['kommentier', 'antworte', 'schreib unter'],
          assign: ['weise', 'zuweisen', 'gib'],
          label: ['label', 'markiere'],
          merge: ['merge', 'zusammenführ'],
          approve: ['genehmige', 'freigeben', 'approve'],
          delete: ['lösche', 'entferne'],
          switch: ['wechsle', 'wechsel'],
          status: ['status', 'grün', 'rot', 'durchgelaufen', 'fehlgeschlagen', 'läuft'],
          rerun: ['neu starten', 'nochmal', 'erneut ausführen'],
          commit: ['committe', 'commit'],
          push: ['push', 'pushe', 'hochladen'],
          pull: ['pull', 'pulle', 'aktualisiere'],
        },
        {
          issue: ['issue', 'ticket', 'fehler', 'aufgabe', 'bug'],
          pr: ['pull request', 'pr', 'merge request', 'mr'],
          branch: ['branch', 'zweig'],
          commit: ['commit', 'commits', 'verlauf'],
          ci: ['ci', 'build', 'pipeline', 'tests'],
          release: ['release'],
          tag: ['tag'],
          label: ['label'],
          repo: ['repo', 'repository', 'projekt'],
        },
        ['an', 'für', 'zu'],
        ['im', 'in', 'auf'],
        ['von', 'aus'],
        ['nach', 'in'],
        ['meine', 'mir'],
      ],
      [
        'fr',
        {
          create: ['crée', 'créer', 'nouveau', 'nouvelle', 'ouvre un', 'ouvre une', 'signale'],
          list: ['liste', 'quels', 'quelles', 'mes'],
          show: ['montre', 'affiche', 'voir'],
          close: ['ferme', 'clôture', 'clos'],
          reopen: ['rouvre', 'réouvre'],
          comment: ['commente', 'réponds', 'écris sous'],
          assign: ['assigne', 'attribue', 'donne'],
          label: ['étiquette', 'label'],
          merge: ['merge', 'fusionne'],
          approve: ['approuve', 'valide'],
          delete: ['supprime', 'efface'],
          switch: ['bascule', 'passe sur', 'change de'],
          status: ['statut', 'passé', 'vert', 'rouge', 'échoué', 'cassé'],
          rerun: ['relance', 'redémarre'],
          commit: ['commite', 'commit'],
          push: ['pousse', 'push'],
          pull: ['tire', 'pull', 'récupère'],
        },
        {
          issue: ['issue', 'ticket', 'bogue', 'anomalie', 'bug', 'tâche'],
          pr: ['pull request', 'pr', 'merge request', 'mr', 'demande de fusion'],
          branch: ['branche'],
          commit: ['commit', 'commits', 'historique'],
          ci: ['ci', 'build', 'pipeline', 'tests'],
          release: ['release', 'version'],
          tag: ['tag'],
          label: ['label', 'étiquette'],
          repo: ['repo', 'dépôt', 'projet'],
        },
        ['à', 'pour'],
        ['dans', 'sur', 'pour'],
        ['de', 'depuis'],
        ['vers', 'dans', 'sur'],
        ['mes', 'moi'],
      ],
      [
        'es',
        {
          create: ['crea', 'nueva', 'nuevo', 'abre un', 'abre una', 'reporta'],
          list: ['lista', 'cuáles', 'cuales', 'mis'],
          show: ['muestra', 'enséñame', 'ver'],
          close: ['cierra', 'cerrar'],
          reopen: ['reabre', 'vuelve a abrir'],
          comment: ['comenta', 'responde'],
          assign: ['asigna', 'dale'],
          label: ['etiqueta'],
          merge: ['fusiona', 'mergea', 'merge'],
          approve: ['aprueba'],
          delete: ['borra', 'elimina'],
          switch: ['cambia a', 'pasa a'],
          status: ['estado', 'pasó', 'verde', 'rojo', 'falló', 'roto'],
          rerun: ['relanza', 'vuelve a ejecutar', 'reintenta'],
          commit: ['commitea', 'haz commit', 'confirma'],
          push: ['sube', 'pushea', 'empuja'],
          pull: ['baja', 'actualiza', 'pullea', 'trae'],
        },
        {
          issue: ['issue', 'incidencia', 'ticket', 'error', 'bug', 'tarea'],
          pr: ['pull request', 'pr', 'merge request', 'mr', 'solicitud de fusión'],
          branch: ['rama'],
          commit: ['commit', 'commits', 'historial'],
          ci: ['ci', 'build', 'pipeline', 'pruebas', 'tests'],
          release: ['release', 'versión'],
          tag: ['tag', 'etiqueta de versión'],
          label: ['etiqueta'],
          repo: ['repo', 'repositorio', 'proyecto'],
        },
        ['a', 'para'],
        ['en', 'del', 'de'],
        ['de', 'desde'],
        ['a', 'en', 'hacia'],
        ['mis', 'mí'],
      ],
      [
        'pt',
        {
          create: ['crie', 'cria', 'novo', 'nova', 'abra um', 'abre um', 'reporte'],
          list: ['liste', 'lista', 'quais', 'meus', 'minhas'],
          show: ['mostre', 'mostra', 'ver'],
          close: ['feche', 'fecha', 'encerre'],
          reopen: ['reabra', 'reabre'],
          comment: ['comente', 'comenta', 'responda'],
          assign: ['atribua', 'atribui', 'designe'],
          label: ['etiqueta', 'rótulo', 'label'],
          merge: ['mescle', 'faça merge', 'merge'],
          approve: ['aprove', 'aprova'],
          delete: ['apague', 'exclua', 'deleta'],
          switch: ['mude para', 'troque para'],
          status: ['status', 'passou', 'verde', 'vermelho', 'falhou', 'quebrou'],
          rerun: ['rode de novo', 'reexecute', 'execute novamente'],
          commit: ['commite', 'faça commit'],
          push: ['envie', 'push', 'suba'],
          pull: ['puxe', 'atualize', 'pull'],
        },
        {
          issue: ['issue', 'chamado', 'erro', 'bug', 'tarefa'],
          pr: ['pull request', 'pr', 'merge request', 'mr'],
          branch: ['branch', 'ramo'],
          commit: ['commit', 'commits', 'histórico'],
          ci: ['ci', 'build', 'pipeline', 'testes'],
          release: ['release', 'versão'],
          tag: ['tag'],
          label: ['etiqueta', 'label'],
          repo: ['repo', 'repositório', 'projeto'],
        },
        ['para', 'a'],
        ['no', 'na', 'em', 'do'],
        ['de', 'da'],
        ['para', 'em'],
        ['meus', 'minhas', 'mim'],
      ],
      [
        'it',
        {
          create: ['crea', 'nuovo', 'nuova', 'apri un', 'apri una', 'segnala'],
          list: ['elenca', 'quali', 'miei', 'mie'],
          show: ['mostra', 'fammi vedere'],
          close: ['chiudi', 'chiudere'],
          reopen: ['riapri'],
          comment: ['commenta', 'rispondi'],
          assign: ['assegna'],
          label: ['etichetta', 'label'],
          merge: ['unisci', 'fai merge', 'merge'],
          approve: ['approva'],
          delete: ['elimina', 'cancella'],
          switch: ['passa a', 'cambia branch'],
          status: ['stato', 'passata', 'verde', 'rosso', 'fallita', 'rotta'],
          rerun: ['rilancia', 'riesegui'],
          commit: ['committa', 'fai commit'],
          push: ['pusha', 'invia'],
          pull: ['aggiorna', 'pulla', 'scarica'],
        },
        {
          issue: ['issue', 'ticket', 'errore', 'bug', 'attività'],
          pr: ['pull request', 'pr', 'merge request', 'mr'],
          branch: ['branch', 'ramo'],
          commit: ['commit', 'cronologia'],
          ci: ['ci', 'build', 'pipeline', 'test'],
          release: ['release', 'versione'],
          tag: ['tag'],
          label: ['etichetta', 'label'],
          repo: ['repo', 'repository', 'progetto'],
        },
        ['a', 'per'],
        ['in', 'nel', 'su'],
        ['da'],
        ['in', 'su'],
        ['miei', 'mie', 'me'],
      ],
      [
        'tr',
        {
          create: ['oluştur', 'aç ', 'yeni', 'ekle', 'bildir'],
          list: ['listele', 'hangi', 'göster tüm', 'açık olan'],
          show: ['göster', 'aç bak'],
          close: ['kapat'],
          reopen: ['yeniden aç', 'tekrar aç'],
          comment: ['yorum', 'cevap yaz', 'yanıtla'],
          assign: ['ata', 'atay'],
          label: ['etiket'],
          merge: ['birleştir', 'merge'],
          approve: ['onayla'],
          delete: ['sil'],
          switch: ['geç', 'geçiş'],
          status: ['durum', 'geçti', 'yeşil', 'kırmızı', 'başarısız', 'kırıldı'],
          rerun: ['yeniden çalıştır', 'tekrar çalıştır'],
          commit: ['commit'],
          push: ['push', 'gönder'],
          pull: ['pull', 'çek', 'güncelle'],
        },
        {
          issue: ['issue', 'hata', 'kayıt', 'görev', 'bug'],
          pr: ['pull request', 'pr', 'merge request', 'mr', 'çekme isteği'],
          branch: ['branch', 'dal'],
          commit: ['commit', 'geçmiş'],
          ci: ['ci', 'build', 'pipeline', 'test'],
          release: ['sürüm', 'release'],
          tag: ['etiket', 'tag'],
          label: ['etiket'],
          repo: ['repo', 'depo', 'proje'],
        },
        ['a', 'e', 'ya', 'ye'],
        ['de', 'da', 'içinde'],
        ['dan', 'den'],
        ['a', 'e'],
        ['benim', 'bana'],
      ],
      [
        'ar',
        {
          create: ['أنشئ', 'انشئ', 'افتح', 'جديد', 'جديدة', 'أضف', 'سجل'],
          list: ['اعرض كل', 'قائمة', 'ما هي', 'مشاكلي', 'تذاكري'],
          show: ['اعرض', 'أرني', 'ارني'],
          close: ['أغلق', 'اغلق', 'سكر'],
          reopen: ['أعد فتح', 'اعد فتح'],
          comment: ['علق', 'علّق', 'رد على'],
          assign: ['عين', 'عيّن', 'أسند', 'اسند'],
          label: ['وسم', 'تسمية'],
          merge: ['ادمج', 'دمج'],
          approve: ['وافق', 'اعتمد'],
          delete: ['احذف', 'امسح'],
          switch: ['انتقل', 'بدّل', 'بدل'],
          status: ['حالة', 'نجح', 'فشل', 'أخضر', 'أحمر'],
          rerun: ['أعد تشغيل', 'اعد تشغيل'],
          commit: ['كوميت', 'commit'],
          push: ['ادفع', 'push'],
          pull: ['اسحب', 'حدث', 'pull'],
        },
        {
          issue: ['مشكلة', 'تذكرة', 'خطأ', 'issue', 'مهمة'],
          pr: ['طلب دمج', 'طلب سحب', 'pr', 'mr'],
          branch: ['فرع'],
          commit: ['كوميت', 'commit', 'سجل'],
          ci: ['ci', 'البناء', 'بناء', 'خط الأنابيب', 'الاختبارات'],
          release: ['إصدار', 'اصدار'],
          tag: ['وسم', 'tag'],
          label: ['تسمية', 'وسم'],
          repo: ['مستودع', 'المستودع', 'مشروع'],
        },
        ['إلى', 'الى', 'ل'],
        ['في', 'على'],
        ['من'],
        ['إلى', 'الى', 'في'],
        ['لي', 'خاصتي'],
      ],
      [
        'zh',
        {
          create: ['创建', '新建', '开一个', '提一个', '报告'],
          list: ['列出', '有哪些', '所有', '我的'],
          show: ['查看', '显示', '看看'],
          close: ['关闭', '关掉'],
          reopen: ['重新打开'],
          comment: ['评论', '回复'],
          assign: ['分配', '指派'],
          label: ['标签', '打上'],
          merge: ['合并'],
          approve: ['批准', '通过'],
          delete: ['删除', '删掉'],
          switch: ['切换', '切到'],
          status: ['状态', '通过了', '失败', '挂了', '绿', '红'],
          rerun: ['重新运行', '重跑', '重试'],
          commit: ['提交'],
          push: ['推送', 'push'],
          pull: ['拉取', '拉一下', '更新'],
        },
        {
          issue: ['问题', '工单', 'issue', '缺陷', 'bug', '任务'],
          pr: ['合并请求', '拉取请求', 'pr', 'mr'],
          branch: ['分支'],
          commit: ['提交记录', 'commit', '历史'],
          ci: ['ci', '构建', '流水线', '测试'],
          release: ['发布', '版本'],
          tag: ['标签', 'tag'],
          label: ['标签'],
          repo: ['仓库', '项目'],
        },
        ['给'],
        ['在', '里'],
        ['从'],
        ['到', '进'],
        ['我的', '给我'],
      ],
    ] as Array<
      [
        string,
        GitSpeech['verbs'],
        Partial<GitSpeech['objects']>,
        string[],
        string[],
        string[],
        string[],
        string[],
      ]
    >
  ).map(
    ([lang, verbs, objects, toPerson, inRepo, from, into, mine]): GitSpeech => ({
      lang,
      ...(lang === 'zh' ? { dense: true } : {}),
      verbs,
      objects: { ...emptyObjects(), ...objects },
      toPerson,
      inRepo,
      from,
      into,
      mine,
      open: [],
      closed: [],
      merged: [],
      all: [],
      remoteCue: [],
      localCue: [],
      labelWord: objects.label ?? [],
      that: [],
    }),
  ),
];

function emptyObjects(): Record<GitObject, string[]> {
  return {
    issue: [],
    pr: [],
    branch: [],
    commit: [],
    ci: [],
    release: [],
    tag: [],
    label: [],
    milestone: [],
    repo: [],
    file: [],
    code: [],
    member: [],
    notification: [],
    account: [],
    local: [],
  };
}

const escapeRe = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/**
 * One pattern for a set of stems: each at the start of a word in a spaced script, anywhere in a
 * dense one. Longest first, so "pull request" is found before "pull".
 */
export function stemPattern(stems: readonly string[], dense = false): RegExp | null {
  // Folded as the sentence is (text.ts): ё is е, Arabic kaf is Persian kaf, ZWNJ is a space.
  const list = [...new Set(stems.map((s) => fold(s).toLowerCase()).filter(Boolean))].sort(
    (a, b) => b.length - a.length,
  );
  if (!list.length) return null;
  const body = list.map((s) => escapeRe(s.trimEnd())).join('|');
  return dense ? new RegExp(`(?:${body})`, 'u') : new RegExp(`(?<![\\p{L}\\p{N}])(?:${body})`, 'u');
}

/** Every language's stems for one thing, as one pattern each for spaced and dense scripts. */
export function speechPattern(pick: (s: GitSpeech) => readonly string[] | undefined): RegExp[] {
  const spaced = GIT_SPEECH.filter((s) => !s.dense).flatMap((s) => pick(s) ?? []);
  const dense = GIT_SPEECH.filter((s) => s.dense).flatMap((s) => pick(s) ?? []);
  return [stemPattern(spaced), stemPattern(dense, true)].filter((r): r is RegExp => r !== null);
}
